from __future__ import annotations

from src.auth import hash_password


SEED_USERS = [
    {
        "username": "admin",
        "full_name": "System Administrator",
        "password_hash": hash_password("admin123"),
        "role": "admin",
    },
    {
        "username": "inspector1",
        "full_name": "Eng. Grace Wanjiru",
        "password_hash": hash_password("inspect123"),
        "role": "inspector",
    },
    {
        "username": "developer1",
        "full_name": "Urban Heights Ltd",
        "password_hash": hash_password("develop123"),
        "role": "developer",
    },
]


SEED_BUILDINGS = [
    {
        "building": {
            "building_name": "Sunrise Residency",
            "location": "Nakuru CBD",
            "number_of_floors": 6,
            "year_of_construction": 2019,
            "intended_use": "Residential Apartments",
            "approved_design_details": "Approved for six floors with reinforced concrete frame.",
            "created_by": 1,
        },
        "structural": {
            "concrete_grade": "C30",
            "reinforcement_steel_type": "TMT",
            "column_dimensions_cm": 32.0,
            "floor_count_compliance": 1,
            "supervision_records": 1,
            "structural_compliance_notes": "Site records and inspection logs were available.",
            "assessed_by": 2,
        },
        "fire": {
            "number_of_staircases": 2,
            "staircase_width_m": 1.4,
            "fire_exits": 2,
            "fire_extinguishers": 14,
            "smoke_detectors": 24,
            "fire_alarms": 1,
            "sprinklers": 1,
            "emergency_lighting": 1,
            "evacuation_route_notes": "Marked escape paths available on each landing.",
            "assessed_by": 2,
        },
        "compliance": {
            "inspector_name": "Eng. Grace Wanjiru",
            "inspector_registration_number": "EBK-4721",
            "developer_name": "Urban Heights Ltd",
            "developer_registration_number": "DEV-0093",
            "approval_status": "Approved",
            "uploaded_document_metadata": "Architectural drawings, Structural drawings, Occupancy permit",
            "verification_status": "Verified",
            "review_notes": "Documentation complete and cross-checked.",
            "assessed_by": 2,
        },
    },
    {
        "building": {
            "building_name": "Greenview Flats",
            "location": "Eldoret Annex",
            "number_of_floors": 4,
            "year_of_construction": 2015,
            "intended_use": "Mixed Residential",
            "approved_design_details": "Approved for four floors; rooftop water tank included.",
            "created_by": 3,
        },
        "structural": {
            "concrete_grade": "C25",
            "reinforcement_steel_type": "Y16",
            "column_dimensions_cm": 26.0,
            "floor_count_compliance": 1,
            "supervision_records": 0,
            "structural_compliance_notes": "Supervision records partially missing.",
            "assessed_by": 2,
        },
        "fire": {
            "number_of_staircases": 1,
            "staircase_width_m": 1.0,
            "fire_exits": 1,
            "fire_extinguishers": 6,
            "smoke_detectors": 8,
            "fire_alarms": 1,
            "sprinklers": 0,
            "emergency_lighting": 1,
            "evacuation_route_notes": "Evacuation plan posted at entrance only.",
            "assessed_by": 2,
        },
        "compliance": {
            "inspector_name": "Eng. Grace Wanjiru",
            "inspector_registration_number": "EBK-4721",
            "developer_name": "Rift Valley Homes",
            "developer_registration_number": "DEV-1148",
            "approval_status": "Conditional",
            "uploaded_document_metadata": "Structural drawings, Fire checklist",
            "verification_status": "Partially Verified",
            "review_notes": "Conditional approval pending staircase signage improvement.",
            "assessed_by": 2,
        },
    },
    {
        "building": {
            "building_name": "Hillside Court",
            "location": "Nairobi South B",
            "number_of_floors": 8,
            "year_of_construction": 2011,
            "intended_use": "Residential Apartments",
            "approved_design_details": "Original permit was issued for seven floors.",
            "created_by": 1,
        },
        "structural": {
            "concrete_grade": "C20",
            "reinforcement_steel_type": "Mild",
            "column_dimensions_cm": 22.0,
            "floor_count_compliance": 0,
            "supervision_records": 0,
            "structural_compliance_notes": "Observed mismatch between permit and actual floor count.",
            "assessed_by": 2,
        },
        "fire": {
            "number_of_staircases": 1,
            "staircase_width_m": 0.85,
            "fire_exits": 1,
            "fire_extinguishers": 4,
            "smoke_detectors": 5,
            "fire_alarms": 0,
            "sprinklers": 0,
            "emergency_lighting": 0,
            "evacuation_route_notes": "Escape route markings were not visible on upper floors.",
            "assessed_by": 2,
        },
        "compliance": {
            "inspector_name": "Eng. Grace Wanjiru",
            "inspector_registration_number": "EBK-4721",
            "developer_name": "Metro Shelter Group",
            "developer_registration_number": "",
            "approval_status": "Rejected",
            "uploaded_document_metadata": "Old permit copy",
            "verification_status": "Unverified",
            "review_notes": "Requires urgent follow-up due to compliance gaps.",
            "assessed_by": 2,
        },
    },
]
